apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfp-deployment
  labels:
    app: dfp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfp
  template:
    metadata:
      labels:
        app: dfp
    spec:
      containers:
      - name: akscidev
        image: akscidev.azurecr.io/aksdev:7
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
